---
title: Raspberry Pi Homelab
description: Панель состояния, навигации и обслуживания

theme: dark
color: slate
language: ru

customJS: /config/custom.js

headerStyle: clean 
hideVersion: true
statusStyle: "badge" 

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: false

layout:
  Дополнительные сервисы:
    style: row
    columns: 4

  Статистика:
    style: row
    columns: 4

  Состояние поднятых систем:
    style: row
    columns: 4

  Документация:
    style: row
    columns: 4
